package com.pesupal.server.service.implementations.chat.group_message;

import com.pesupal.server.config.StaticConfig;
import com.pesupal.server.dto.request.chat.RescheduleMessageDto;
import com.pesupal.server.dto.request.chat.direct_message.ChatMessageDto;
import com.pesupal.server.dto.request.chat.group_message.GetGroupConversationDto;
import com.pesupal.server.dto.response.UserPreviewDto;
import com.pesupal.server.dto.response.chat.MediaFileDto;
import com.pesupal.server.dto.response.chat.MessageDto;
import com.pesupal.server.enums.MessageType;
import com.pesupal.server.exceptions.ActionProhibitedException;
import com.pesupal.server.exceptions.DataNotFoundException;
import com.pesupal.server.exceptions.PermissionDeniedException;
import com.pesupal.server.helpers.CurrentValueRetriever;
import com.pesupal.server.helpers.InputValidator;
import com.pesupal.server.model.chat.MessageStatus;
import com.pesupal.server.model.chat.group_message.*;
import com.pesupal.server.model.org.Org;
import com.pesupal.server.model.user.OrgMember;
import com.pesupal.server.repository.chat.group_message.GroupChatMemberRepository;
import com.pesupal.server.repository.chat.group_message.GroupChatMessageRepository;
import com.pesupal.server.repository.chat.group_message.GroupMessageMediaFileRepository;
import com.pesupal.server.security.JwtUtil;
import com.pesupal.server.service.interfaces.chat.group_message.*;
import com.pesupal.server.service.interfaces.org.OrgMemberService;
import com.pesupal.server.strategies.media_storage.S3Service;
import io.jsonwebtoken.Claims;
import lombok.AllArgsConstructor;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;

@Service
@AllArgsConstructor
@Qualifier("groupChatMessageService")
public class GroupChatMessageServiceImpl extends CurrentValueRetriever implements GroupChatMessageService {

    private final JwtUtil jwtUtil;
    private final S3Service s3Service;
    private final GroupService groupService;
    private final OrgMemberService orgMemberService;
    private final GroupChatMemberService groupChatMemberService;
    private final GroupChatReactionService groupChatReactionService;
    private final GroupChatMemberRepository groupChatMemberRepository;
    private final GroupChatMessageRepository groupChatMessageRepository;
    private final GroupMessageMediaFileService groupMessageMediaFileService;
    private final GroupChatConfigurationService groupChatConfigurationService;
    private final GroupMessageMediaFileRepository groupMessageMediaFileRepository;

    /**
     * Retrieves a group chat message by its ID.
     *
     * @param messageId
     * @return
     */
    @Override
    public GroupChatMessage getGroupChatMessageById(Long messageId) {

        return groupChatMessageRepository.findById(messageId).orElseThrow(() -> new DataNotFoundException("Group message not found with ID " + messageId + "."));
    }

    /**
     * Deletes a group message.
     *
     * @param messageId
     */
    @Transactional
    @Override
    public void deleteGroupMessage(Long messageId) {

        OrgMember orgMember = getCurrentOrgMember();
        Long userId = orgMember.getId();
        GroupChatMessage groupChatMessage = getGroupChatMessageById(messageId);
        Group group = groupChatMessage.getGroup();
        if (!group.getOrg().getId().equals(orgMember.getOrg().getId())) {
            throw new DataNotFoundException("Message not found in this organization.");
        }

        GroupChatMember groupChatMember = groupChatMemberService.getGroupMemberByGroupIdAndUserId(group.getId(), userId);
        if (!groupChatMember.isActive()) {
            throw new PermissionDeniedException("You're not part of this group anymore.");
        }

        if (!group.isActive()) {
            throw new ActionProhibitedException("This group is no longer active.");
        }

        if (groupChatMessage.getMessageStatus().equals(MessageStatus.DELETED)) {
            throw new ActionProhibitedException("This message has already been deleted.");
        }

        if (!groupChatMessage.getSender().getId().equals(userId)) {
            throw new PermissionDeniedException("You do not have permission to delete this message.");
        }

        if (!groupChatMessage.getMessageType().equals(MessageType.USER_MESSAGE)) {
            throw new PermissionDeniedException("You cannot delete the message generated by the system.");
        }

        GroupChatConfiguration groupChatConfiguration = groupChatConfigurationService.getConfigurationByGroupAndRole(group, groupChatMember.getRole());
        if (!groupChatConfiguration.isDeleteMessage()) {
            throw new PermissionDeniedException("You do not have permission to delete messages from this group.");
        }

        groupChatMemberRepository.updateLastReadMessageToNull(groupChatMessage);

        groupChatMessage.setMessageStatus(MessageStatus.DELETED);
        groupChatMessageRepository.save(groupChatMessage);

        groupMessageMediaFileService.unlinkMediaFilesByGroupMessage(groupChatMessage);
    }

    /**
     * Retrieves messages from a group chat based on the provided criteria.
     *
     * @param getGroupConversationDto
     * @return
     */
    @Override
    public List<MessageDto> getGroupChatMessages(GetGroupConversationDto getGroupConversationDto) {

        OrgMember orgMember = getCurrentOrgMember();
        Long orgId = orgMember.getOrg().getId();

        Pageable pageable = PageRequest.of(
                getGroupConversationDto.getPage(),
                getGroupConversationDto.getSize(),
                Sort.by("createdAt").descending());
        Page<GroupChatMessage> messages = null;
        Long pivotMessageId = getGroupConversationDto.getPivotMessageId();
        List<MessageStatus> fetchMessagesWithStatus = List.of(MessageStatus.SENT, MessageStatus.DELETED);
        if (pivotMessageId != null) {
            messages = groupChatMessageRepository.findAllByGroup_PublicIdAndIdLessThanAndMessageStatusIn(getGroupConversationDto.getGroupId(), getGroupConversationDto.getPivotMessageId(), fetchMessagesWithStatus, pageable);
        } else {
            messages = groupChatMessageRepository.findAllByGroup_PublicIdAndMessageStatusIn(getGroupConversationDto.getGroupId(), fetchMessagesWithStatus, pageable);
        }
        Map<Long, UserPreviewDto> memo = new HashMap<>();
        return messages.stream().map(gm -> {
            MessageDto messageDto = MessageDto.fromGroupMessage(gm);
            Long senderId = gm.getSender().getId();
            if (!memo.containsKey(senderId)) {
                memo.put(senderId, UserPreviewDto.fromOrgMember(orgMemberService.getOrgMemberByUserIdAndOrgId(senderId, orgId)));
            }
            messageDto.setSender(memo.get(senderId));
            if (gm.isContainsMedia()) {
                Optional<GroupMessageMediaFile> optionalGroupMessageMediaFile = groupMessageMediaFileRepository.findByGroupChatMessage(gm);
                if (optionalGroupMessageMediaFile.isPresent()) {
                    GroupMessageMediaFile groupMessageMediaFile = optionalGroupMessageMediaFile.get();
                    MediaFileDto mediaFileDto = MediaFileDto.fromGroupMessageMediaFile(groupMessageMediaFile);
                    String key = groupMessageMediaFile.getMediaId() + "." + groupMessageMediaFile.getExtension();
                    mediaFileDto.setMediaUrl(s3Service.generatePresignedUrl(key));
                    messageDto.setMedia(mediaFileDto);
                }
            }
            messageDto.setReactions(groupChatReactionService.getReactionsCountForMessage(gm));
            return messageDto;
        }).sorted(Comparator.comparing(MessageDto::getCreatedAt)).toList();
    }

    /**
     * Clears all messages in a group chat.
     *
     * @param groupId
     */
    @Transactional
    @Override
    public void clearGroupChatMessages(String groupId) {

        OrgMember orgMember = getCurrentOrgMember();
        Long userId = orgMember.getId();
        Long orgId = orgMember.getOrg().getId();

        GroupChatMember groupChatMember = groupChatMemberService.getGroupMemberByGroupIdAndUserId(groupId, userId);
        Group group = groupChatMember.getGroup();

        if (!group.getOrg().getId().equals(orgId)) {
            throw new DataNotFoundException("Group with ID " + groupId + " does not exist.");
        }

        if (!groupChatMember.isActive()) {
            throw new PermissionDeniedException("You're not part of this group anymore.");
        }

        if (!group.isActive()) {
            throw new ActionProhibitedException("This group is no longer active.");
        }

        GroupChatConfiguration groupChatConfiguration = groupChatConfigurationService.getConfigurationByGroupAndRole(group, groupChatMember.getRole());
        if (!groupChatConfiguration.isClearChat()) {
            throw new PermissionDeniedException("You do not have permission to clear messages in this group.");
        }

        // Set last read message to null for all members in the group to ensure that the members are not removed from the group
        groupChatMemberRepository.updateAllLastReadMessageToNullByGroup(group);

        groupMessageMediaFileService.unlinkAllMediaFilesByGroup(group);

        groupChatReactionService.deleteAllByGroup(group);

        groupChatMessageRepository.deleteAllByGroupAndMessageStatusIn(group, List.of(MessageStatus.SENT, MessageStatus.DELETED));

        addSystemMessage(group, orgMember.getDisplayName() + " has cleared the group chat messages.");
    }

    /**
     * Marks all messages in a group as read.
     *
     * @param groupId
     */
    @Override
    public void markAllGroupMessagesAsRead(String groupId) {

        OrgMember orgMember = getCurrentOrgMember();
        Long userId = orgMember.getId();

        GroupChatMember groupChatMember = groupChatMemberService.getGroupMemberByGroupIdAndUserId(groupId, userId);
        if (!groupChatMember.isActive()) {
            throw new PermissionDeniedException("You're not part of this group anymore.");
        }

        Group group = groupChatMember.getGroup();
        Optional<GroupChatMessage> lastMessageOfGroup = groupChatMessageRepository.findFirstByGroupOrderByCreatedAtDesc(group);
        lastMessageOfGroup.ifPresent(groupChatMember::setLastReadMessage);

        groupChatMemberRepository.save(groupChatMember);
    }

    /**
     * Converts a DirectMessage entity to a MessageDto.
     *
     * @param gm
     * @param orgId
     * @param memo
     * @return
     */
    private MessageDto toMessageDto(GroupChatMessage gm, Long orgId, Map<Long, UserPreviewDto> memo) {

        MessageDto messageDto = MessageDto.fromGroupMessage(gm);
        Long senderId = gm.getSender().getId();
        if (!memo.containsKey(senderId)) {
            memo.put(senderId, UserPreviewDto.fromOrgMember(orgMemberService.getOrgMemberByUserIdAndOrgId(senderId, orgId)));
        }
        messageDto.setSender(memo.get(senderId));
        if (gm.isContainsMedia()) {
            Optional<GroupMessageMediaFile> optionalGroupMessageMediaFile = groupMessageMediaFileRepository.findByGroupChatMessage(gm);
            if (optionalGroupMessageMediaFile.isPresent()) {
                GroupMessageMediaFile groupMessageMediaFile = optionalGroupMessageMediaFile.get();
                MediaFileDto groupMessageMediaFileDto = MediaFileDto.fromGroupMessageMediaFile(groupMessageMediaFile);
                String key = groupMessageMediaFile.getMediaId() + "." + groupMessageMediaFile.getExtension();
                groupMessageMediaFileDto.setMediaUrl(s3Service.generatePresignedUrl(key));
                messageDto.setMedia(groupMessageMediaFileDto);
            }
        }
        messageDto.setReactions(groupChatReactionService.getReactionsCountForMessage(gm));
        return messageDto;
    }

    /**
     * Saves a chat message.
     *
     * @param chatMessageDto
     * @return
     */
    @Override
    @Transactional
    public MessageDto save(ChatMessageDto<GroupChatMessage> chatMessageDto) {

        String token = (String) InputValidator.notNull(chatMessageDto.getToken(), "token");

        Claims claims = jwtUtil.extractAllClaims(token);
        String senderOrgMemberId = claims.get("orgMemberId").toString();

        OrgMember sender = orgMemberService.getOrgMemberByPublicId(senderOrgMemberId);
        Org org = sender.getOrg();

        chatMessageDto.setSenderId(sender.getPublicId());

        String groupId = chatMessageDto.getChatId();

        GroupChatMember groupChatMember = groupChatMemberService.getGroupMemberByGroupIdAndUserId(groupId, sender.getId());
        if (!groupChatMember.isActive()) {
            throw new PermissionDeniedException("You are no longer part of this group.");
        }

        Group group = groupService.getGroupByPublicId(groupId);
        if (!group.isActive()) {
            throw new PermissionDeniedException("This group is no longer active.");
        }

        GroupChatConfiguration groupChatConfiguration = groupChatConfigurationService.getConfigurationByGroupAndRole(group, groupChatMember.getRole());
        if (!groupChatConfiguration.isPostMessage()) {
            throw new PermissionDeniedException("You do not have permission to post messages in this group.");
        }

        boolean containsMedia = chatMessageDto.getMedia() != null;

        GroupChatMessage groupChatMessage = new GroupChatMessage();
        groupChatMessage.setGroup(group);
        groupChatMessage.setSender(sender);
        groupChatMessage.setMessage(chatMessageDto.getMessage());
        groupChatMessage.setContainsMedia(containsMedia);
        groupChatMessage.setMessageStatus(MessageStatus.SENT);
        if (chatMessageDto.getMessageStatus().equals(MessageStatus.SCHEDULED)) {
            int maxScheduleLimit = StaticConfig.MAXIMUM_MESSAGES_SCHEDULABLE_PER_CHAT;
            int numberOfScheduledMessages = groupChatMessageRepository.countByGroup_PublicIdAndMessageStatus(chatMessageDto.getChatId(), MessageStatus.SCHEDULED);
            if (numberOfScheduledMessages >= maxScheduleLimit) {
                throw new ActionProhibitedException("You can only schedule a maximum of " + maxScheduleLimit + " messages per group chat at a time.");
            }
            if (chatMessageDto.getScheduleAt() == null) {
                throw new ActionProhibitedException("Scheduled messages must have a schedule time.");
            }
            if (chatMessageDto.getScheduleAt().isBefore(LocalDateTime.now())) {
                throw new ActionProhibitedException("Messages cannot be scheduled in the past.");
            }
            groupChatMessage.setMessageStatus(MessageStatus.SCHEDULED);
            groupChatMessage.setCreatedAt(chatMessageDto.getScheduleAt());
        }
        groupChatMessage = groupChatMessageRepository.save(groupChatMessage);
        if (containsMedia) { // Store media file if present
            GroupMessageMediaFile groupMessageMediaFile = GroupMessageMediaFile.fromMediaUploadDto(chatMessageDto.getMedia());
            groupMessageMediaFile.setGroupChatMessage(groupChatMessage);
            groupMessageMediaFileRepository.save(groupMessageMediaFile);
        }
        return toMessageDto(groupChatMessage, org.getId(), new HashMap<>());
    }

    /**
     * Get the active chat member of the given group to broadcast the message.
     *
     * @param groupId
     * @return
     */
    protected List<GroupChatMember> getActiveMembersOfGroup(String groupId) {

        return groupChatMemberRepository.findAllByGroup_PublicId(groupId);
    }

    /**
     * Broadcasts a message to all subscribers of the topic.
     *
     * @param messageDto
     * @param messagingTemplate
     */
    @Override
    public void broadcastMessage(MessageDto messageDto, SimpMessagingTemplate messagingTemplate) {

        List<GroupChatMember> groupChatMembers = getActiveMembersOfGroup(messageDto.getChatId());
        for (GroupChatMember groupChatMember : groupChatMembers) {
            String userId = groupChatMember.getParticipant().getPublicId();
            messagingTemplate.convertAndSend("/topic/group-message." + userId, messageDto);
        }
    }

    /**
     * Schedules a message to be sent later.
     *
     * @param chatMessageDto
     */
    public void schedule(ChatMessageDto<GroupChatMessage> chatMessageDto) {

        chatMessageDto.setMessageStatus(MessageStatus.SCHEDULED);
        save(chatMessageDto);
    }

    /**
     * Retrieves scheduled messages for a specific chat.
     *
     * @param groupId
     * @return
     */
    @Override
    public List<MessageDto> getScheduledMessages(String groupId) {

        OrgMember orgMember = getCurrentOrgMember();
        Long orgId = orgMember.getOrg().getId();

        GroupChatMember groupChatMember = groupChatMemberService.getGroupMemberByGroupIdAndUserId(groupId, orgMember.getId());
        if (!groupChatMember.isActive()) {
            throw new PermissionDeniedException("You are no longer part of this group.");
        }

        List<GroupChatMessage> scheduledMessages = groupChatMessageRepository.findAllByGroup_PublicIdAndMessageStatus(groupId, MessageStatus.SCHEDULED);

        Map<Long, UserPreviewDto> memo = new HashMap<>();
        return scheduledMessages.stream().map(gm -> toMessageDto(gm, orgId, memo)).sorted(Comparator.comparing(MessageDto::getCreatedAt)).toList();
    }

    /**
     * Reschedules a message to be sent at a later time.
     *
     * @param messageId
     * @param rescheduleMessageDto
     */
    @Override
    public void reschedule(Long messageId, RescheduleMessageDto rescheduleMessageDto) {

        OrgMember orgMember = getCurrentOrgMember();
        GroupChatMessage groupChatMessage = getGroupChatMessageById(messageId);

        if (!groupChatMessage.getSender().getId().equals(orgMember.getId())) {
            throw new PermissionDeniedException("You do not have permission to reschedule this message.");
        }

        if (!groupChatMessage.getMessageStatus().equals(MessageStatus.SCHEDULED)) {
            throw new ActionProhibitedException("This message is not scheduled for rescheduling.");
        }

        if (rescheduleMessageDto.getScheduleAt() == null) {
            throw new ActionProhibitedException("Scheduled messages must have a schedule time.");
        }

        if (rescheduleMessageDto.getScheduleAt().isBefore(LocalDateTime.now())) {
            throw new ActionProhibitedException("Messages cannot be scheduled in the past.");
        }

        groupChatMessage.setCreatedAt(rescheduleMessageDto.getScheduleAt());
        groupChatMessageRepository.save(groupChatMessage);
    }

    /**
     * Unschedules a message, removing it from the scheduled state.
     *
     * @param messageId
     */
    @Override
    public void unschedule(Long messageId) {

    }

    /**
     * Deletes a scheduled message.
     *
     * @param messageId
     */
    @Override
    public void deleteSchedule(Long messageId) {

        OrgMember orgMember = getCurrentOrgMember();
        GroupChatMessage groupChatMessage = getGroupChatMessageById(messageId);

        if (!groupChatMessage.getSender().getId().equals(orgMember.getId())) {
            throw new PermissionDeniedException("You do not have permission to delete this scheduled message.");
        }

        if (!groupChatMessage.getMessageStatus().equals(MessageStatus.SCHEDULED)) {
            throw new ActionProhibitedException("This message is not scheduled for deletion.");
        }

        groupMessageMediaFileService.unlinkMediaFilesByGroupMessage(groupChatMessage);
        groupChatMessageRepository.delete(groupChatMessage);
    }

    /**
     * Deletes all scheduled messages for a specific chat.
     *
     * @param groupId
     */
    @Override
    public void deleteAllScheduledMessages(String groupId) {

        OrgMember orgMember = getCurrentOrgMember();
        Group group = groupService.getGroupByPublicId(groupId);

        GroupChatMember groupChatMember = groupChatMemberService.getGroupMemberByGroupIdAndUserId(groupId, orgMember.getId());
        if (!groupChatMember.isActive()) {
            throw new PermissionDeniedException("You are no longer part of this group.");
        }

        if (!group.isActive()) {
            throw new ActionProhibitedException("This group is no longer active.");
        }

        GroupChatConfiguration groupChatConfiguration = groupChatConfigurationService.getConfigurationByGroupAndRole(group, groupChatMember.getRole());
        if (!groupChatConfiguration.isDeleteMessage()) {
            throw new PermissionDeniedException("You do not have permission to delete messages from this group.");
        }

        List<GroupChatMessage> scheduledMessages = groupChatMessageRepository.findAllByGroupAndSenderAndMessageStatus(group, orgMember, MessageStatus.SCHEDULED);
        for (GroupChatMessage scheduledMessage : scheduledMessages) {

            groupMessageMediaFileService.unlinkMediaFilesByGroupMessage(scheduledMessage);
            groupChatMessageRepository.delete(scheduledMessage);
        }
    }

    /**
     * Adds a system message to a group chat.
     *
     * @param group
     * @param message
     */
    @Override
    public void addSystemMessage(Group group, String message) {

        GroupChatMessage groupChatMessage = new GroupChatMessage();
        groupChatMessage.setGroup(group);
        groupChatMessage.setSender(getCurrentOrgMember());
        groupChatMessage.setMessage(message);
        groupChatMessage.setContainsMedia(false);
        groupChatMessage.setMessageStatus(MessageStatus.SENT);
        groupChatMessage.setMessageType(MessageType.SYSTEM_MESSAGE);
        groupChatMessageRepository.save(groupChatMessage);
    }
}
